# Generated by Django 6.0.3 on 2026-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('emergency_raised', 'Emergency Raised'), ('emergency_approved', 'Emergency Approved'), ('emergency_rejected', 'Emergency Rejected'), ('vote_cast', 'Vote Cast'), ('payout_success', 'Payout Successful'), ('payout_failed', 'Payout Failed'), ('contribution_due', 'Contribution Due'), ('contribution_confirmed', 'Contribution Confirmed')], max_length=30)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('sms', 'SMS'), ('both', 'In App + SMS')], default='both', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('at_message_id', models.CharField(blank=True, max_length=100)),
                ('at_cost', models.CharField(blank=True, max_length=20)),
                ('at_status_code', models.CharField(blank=True, max_length=10)),
                ('raw_response', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sms_logs',
            },
        ),
    ]
