# Generated by Django 6.0.3 on 2026-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='at_cost',
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='at_message_id',
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='at_status_code',
        ),
        migrations.AddField(
            model_name='smslog',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smslog',
            name='provider_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
