# Generated by Django 4.2.9

from django.db import migrations, models


def delete_plaintext_otps(apps, schema_editor):
    OTPCode = apps.get_model('users', 'OTPCode')
    OTPCode.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_plaintext_otps, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(
                help_text='Hashed OTP (never store plaintext).',
                # 255 so 0002-only deploys never truncate password-style hashes.
                max_length=255,
            ),
        ),
    ]
