# Generated by Django 4.2.9
# Keeps upgrade path for DBs that applied 0002 when it used max_length=128.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_code_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(
                help_text='Hashed OTP (never store plaintext).',
                max_length=255,
            ),
        ),
    ]
