# Generated by Django 6.0.3 on 2026-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('stk_push', 'STK Push (C2B)'), ('b2c', 'B2C Payout')], max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='initiated', max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.TextField(blank=True)),
                ('raw_callback', models.JSONField(default=dict)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='emergency_id or contribution_id depending on tx_type', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpesa_transactions',
            },
        ),
    ]
