# Generated by Django 6.0.3 on 2026-03-29 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mpesa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['mpesa_receipt'], name='mpesa_trans_mpesa_r_4ee2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='mpesa_trans_checkou_3d1894_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['user', 'tx_type', 'status'], name='mpesa_trans_user_id_a17959_idx'),
        ),
    ]
