# Generated by Django 6.0.3 on 2026-03-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='Safaricom TransactionID returned in callback metadata (distinct from receipt number)', max_length=50, null=True),
        ),
    ]
