# Generated by Django 6.0.3 on 2026-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('mpesa_ref', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('period', models.CharField(help_text='YYYY-MM (monthly), YYYY-WNN (weekly e.g. 2024-W03), YYYY-MM-DD (daily)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contributions',
            },
        ),
    ]
