# Generated by Django 6.0.3 on 2026-03-29 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['group', 'status'], name='contributio_group_i_d489fc_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member', 'period'], name='contributio_member__5cd06c_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['mpesa_ref'], name='contributio_mpesa_r_925ad6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('group', 'member', 'period')},
        ),
    ]
