# Generated by Django 6.0.3 on 2026-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emergency_approvals',
            },
        ),
        migrations.CreateModel(
            name='EmergencyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='emergency_docs/%Y/%m/')),
                ('label', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emergency_documents',
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('hospitalization', 'Hospitalization'), ('surgery', 'Surgery'), ('medication', 'Medication'), ('maternity', 'Maternity'), ('other', 'Other Medical')], max_length=20)),
                ('description', models.TextField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid Out'), ('failed', 'Payout Failed')], default='pending', max_length=15)),
                ('payout_phone', models.CharField(help_text='Phone to disburse to (Safaricom)', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('mpesa_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emergency_requests',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('paybill', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'hospitals',
            },
        ),
    ]
