# Generated by Django 6.0.3 on 2026-03-29 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencies', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyapproval',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergencies', to='groups.group'),
        ),
        migrations.AddField(
            model_name='emergencydocument',
            name='emergency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='emergencies.emergencyrequest'),
        ),
        migrations.AddField(
            model_name='emergencyapproval',
            name='emergency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='emergencies.emergencyrequest'),
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['group', 'status'], name='emergency_r_group_i_3d754b_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['claimant', 'status'], name='emergency_r_claiman_c687fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencyapproval',
            unique_together={('emergency', 'admin')},
        ),
    ]
