# Generated by Django 6.0.3 on 2026-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('invite_code', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', help_text='How often members are expected to contribute', max_length=10)),
                ('contribution_deadline_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1-28) for monthly; day of week (0=Mon…6=Sun) for weekly; unused for daily', null=True)),
                ('contribution_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed per-period contribution amount in KES', max_digits=10, null=True)),
                ('paybill_number', models.CharField(blank=True, help_text='Safaricom paybill or till number for C2B collections', max_length=20)),
                ('min_contributions_to_qualify', models.PositiveIntegerField(default=3)),
                ('max_payout_amount', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('approval_threshold', models.PositiveIntegerField(default=3, help_text='Number of admin approvals required to release funds')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('left', 'Left')], default='active', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'group_members',
            },
        ),
    ]
