# Generated by Django 6.0.3 on 2026-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('paybill', 'PayBill'), ('buy_goods', 'Buy Goods')], default='buy_goods', help_text='M-Pesa payment type: paybill (CustomerPayBillOnline) or buy_goods (CustomerBuyGoodsOnline)', max_length=10),
        ),
    ]
